= Module 07: Testing, Debugging, Exceptions, Assertions

== 우리는 고품질을 목표로 합니다 – 수프와 유사합니다

수프를 만들고 있는데 천장에서 벌레가 계속 떨어지네요. 어떡할건가요?

* 수프에 벌레가 있는지 확인
** 테스트
* 뚜껑을 닫아둔다
** 방어적 프로그래밍
* 주방 청소
** 소스의 버그 제거

image:./images/image01.png[]

image:./images/image02.png[]

== 쉬운 테스트와 디버깅을 위한 설정

* **처음**부터 이 부분을 쉽게 할 수 있도록 코드를 디자인
* 프로그램을 개별적으로 테스트하고 디버깅할 수 있는 **모듈**로 나눔
* 모듈에 대한 **문서 제약**
** 입력이 어떻게 될 것으로 예상합니까?
** 결과가 어떻게 될 것으로 예상합니까?
* 코드 설계 뒤에 있는 **가정을 문서화**합니다.

== 언제 테스트할 준비가 되는가?

* **코드 실행**이 보장될 때
** Syntax error 제거
** Static semantic error를 제거합니다.
** Python 인터프리터는 일반적으로 이러한 항목을 찾아줄 수 있습니다.
* **예상되는 결과 세트**가 있음
** 입력 세트
** 각 입력에 대해 예상되는 출력

== 테스트 분류

* Unit testing
** 프로그램의 각 조각 검증
** 각 **함수를 분리하여 테스팅**
* Regression testing
** 버그를 발견하면 테스트를 추가
** 이전에 수정된 오류를 **다시 찾아냄**
* Integration testing
** **전반적인 프로그램**이 작동하는가?
** 이 일을 서두르는 경향이 있다

== 테스트 접근 방식

* 문제의 자연스러운 경계에 대한 직관적인 접근

[source, python]
----
def is_bigger(x, y):
    """ Assumes x and y are ints
    Returns True if y is less than x, else False """
----

** 자연스럽게 경계를 구분할 수 있는가?
* 자연스러운 파티션이 없으면 **랜덤 테스트(Random Test)**를 수행할 수 있음
** 코드가 올바를 확률은 테스트의 양과 비례함
** 아래는 더 나은 방법
* 블랙박스(Black Box) 테스트
** Specification을 통해 경로를 탐색
* 유리상자(Glass Box) 테스트
** 코드를 통해 경로를 탐색

== Black box Testing

[source, python]
----
def sqrt(x, eps):
    """ x, eps는 부동 소수점, x >= 0. eps > 0 이라고 가정
    x - eps <= res * res <= x + eps를 return. """
----

* 코드를 **보지 않고** 디자인
* 코드를 구현한 사람의 **편견**을 피하기 위해 다른 사람이 수행할 수 있음
* 구현이 변경되면 테스트를 재사용할 수 있음
* Specification을 통해 경로를 탐색
** 다양한 파티션에 테스트 케이스를 구축
** 경계 조건(빈 목록, 싱글턴 목록, 큰수, 작은 수 등)을 고려

== Black box Testing

[source, python]
----
def sqrt(x, eps):
    """ x, eps는 부동 소수점, x >= 0. eps > 0 이라고 가정
    x - eps <= res * res <= x + eps를 return. """
----

[cols="1, 1, 1" options=header]
|===
|case | x | eps

|boundary | 0 | 0.0001
|perfect square | 25 | 0.0001
|less than 1 | 0.05 | 0.0001
|irrational square root | 2 | 0.0001
|extremes |2  |1.0/2.0**64.0
|extremes |1.0/2.0**64.0 |1.0/2.0**64.0
|extremes |2.0**64.0 |1.0/2.0**64.0
|extremes |1.0/2.0**64.0 |2.0**64.0
|extremes |2.0**64.0 |2.0**64.0
|===

== Glass box Testing

* **코드를 직접 사용**하여 테스트 설계를 설계하도록 가이드
* 코드를 통한 모든 잠재적 코드가 적어도 한번 테스트 되면 **_path-complete_** 라고 함
* Glass box 테스트의 **단점**
** 임의적으로 여러번 루프를 통과할 수 있음
** 경로가 누락될 수 있음
* 지침
** 지점(branch): 모든 상태에 대한 부분을 실행해야 함
** for loop: 반복이 시작되는 경우와 안되는 경우 테스트/반복의 body를 무조건 한번 테스트/반복의 body를 무조건 한번 이상 테스트
** while loop: for loop와 같음, 추가로 반복을 빠져나가는 상태에 대해 테스트

== Glass box Testing

[source, python]
----
def abs(x):
    """ x는 정수(int)라고 가정
    x가 x x> = 0 이면 x를, 아니면 -x를 반환 """

    if x < -1:
        return -x
    else
        return x
----

* path-complete 테스트 스위트는 **버그를 놓칠 수 있음**
* path-complete 테스트 스위트: 2와 -2
* 그러나 abs(-1)은 -1을 return
* boundary case를 계속 테스트 해야 함

== 디버깅

* 가파른 학습 곡선
* 목표는 버그 없는 프로그램을 만드는 것
* 도구
** IDLE (Anaconda에 **내장**)
** **Python tutor**
** `print` statement
** 우리의 뛰어난 머리, **쳬계적인** 사고 방식

== `print` statement

* 가설을 테스트하는 좋은 방법
* 언제 print하는가
** 함수에 들어갈 때
** 파라미터
** 함수의 결과
* **이분법(bisection method)**
** 코드 중간에 print 넣기
** 값에 따라 버그가 있을 수 있는 위치 결정

== 디버깅 단계

* 프로그램 코드를 연구
** 무엇이 틀렸는지 묻지 마라
** 예상하지 못한 결과를 어떻게 얻었는지 물어보라

* 과학적인 방법
** 이용가능한 데이터 연구
** 가설 형성
** 반복 가능한 실험
** 테스트할 가장 간단한 입력 선택

== 오류 메시지가 있다: 쉬움

* 리스트의 한계를 넘어선 액세스 시도:

[source, python]
----
test = [1,2,3]  # index error
----

* 부적절한 타입으로 변환 시도:

[source, python]
----
int(test)   # type error
----

* 존재하지 않는 변수 참조:

[source, python]
----
a   # Name error
----

* 적절한 강제적 조치 없이 데이터 타입 혼합

[source, python]
----
'3' / 4   # Typeerror
----

* 닫는 괄호, 따옴표 등을 잊음

[source, python]
----
a = len([1,2,3]
print(a)    #SyntaxError
----

== 논리 오류(Logic Error) - 어려움

* 새 코드를 작성하기 전에 많은 고려가 필요함
* 잠시 쉬세요
* 코드를 설명해 주세요
** 다른 사람에게
** 벽에 대고

== Don't a and Do

[cols="1a,1a" options=header]
|===
|Don't | Do
| 전체 프로그램 코드를 쓴다 | 함수를 쓴다
| 전체 프로그램을 테스트한다 | 함수를 쓰고, 함수를 테스트
| 전체 프로그램을 디버깅한다 
| * 함수를 쓴다
* 함수를 테스트하고, 함수를 디버그한다.
* 통합 테스트한다.

| |

| 코드 변경 | 코드 백업
| 버그가 어디 있는지 기억 | 코드 변경
| 테스트 코드 | 잠재적인 버그가 있는 곳에 주석 기록
| 버그가 어디 있는지 잊어버리거나 변경한 코드를 잊어버림 | 코드를 테스트
| 환장한다 | 새 버전과 지난 버전 코드 비교
|===

== Exception과 Assertion

* 프로시저의 실행이 예상하지 못한 상황에 직면하면 어떻게 되나?
* **예외(exception)**가 발생한다. -- 이는 예상 헀던 것
** list의 한계를 넘어선 액세스 시도:
+
[source, python]
----
test = [1, 7, 4]
text[4]     # index error
----
+
** 부적절한 타입 변환 시도:
+
[source, python]
----
int(test)   # type error
----
+
** 존재하지 않는 변수 참조
+
[source, python]
----
a   # Name error
----
+
** 비 강제적인 데이터 타입 혼합
+
[source, python]
----
'a' / 4   # Type error
----


== 기타 예외 유형

* 살펴본 일반적인 오류 유형
** SyntaxError: Python이 프로그램을 구문 분석할 수 없음
** NameError: local 또는 global에서 이름을 찾을 수 없음
** AttributeError: 속성 참조 실패
** TypeError: 피 연산자의 유형이 올바르지 않음
** ValueError: 피 연산자의 유형은 괜찮으나 값이 잘못 됨
** IOError: IO 시스템이 오작동을 보고함(예: 파일을 찾을 수 없음)

== 예외 처리

* Python 코드는 **예외 처리기(exception handling)**를 제공
+
[source, python]
----
try:
    a = int(input("Tell me one number: "))
    b = int(input("Tell me another number: "))
except:
    print("Bug in user input.")
----
+
* `try` 본문의 모든 문에서 **일어난(raised)** 예외는 `except` 문에 의해 **처리(handled)**되고 실행은 except 문의 본문으로 계속됨

== 특정 예외 처리

* 특정 타입의 예외를 처리하기 위한 별도의 exception 절을 가짐

[source, python]
----
try:
    a = int(input("Tell me one number: "))
    b = int(input("Tell me another number: "))
    print("a/b = ", a/b)
    print("a+b = ", a+b)
except ValueError:  # try의 코드 중 ValueError 만 처리
    print("Could not convert to a number.")
except ZeroDivisionError:   # try의 코드 중 ZeroDivisionError만 처리
    print("Can't divide by zero")
except: # 모든 예외 처리
    print("Something went very wrong.")
----

== 기타 예외
* `else:`
** 관련 try body의 실행이 예외없이 완료되면 else의 body가 실행됨
* `finally:`
** finally의 body는 다른 오류가 발생했거나 `break`, `continue`, `return`을 실행한 경우에도 `try`, `else`, `except` 절 다음에 항상 실행됨
** 예외가 발생하더라도 실행되어야 하는 정리 코드에 유용(예: 파일 닫기)

== 예외 처리를 위해 해야 할 것

* 오류가 발생하면 어떻게 해야 할까?
* 조용히 실패 처리:
** 기본 값을 대체하거나 계속 진행
** 사용자에게 경고가 표시되지 않음: 좋지 않음
* `error` 값을 반환
** 어떤 값을 선택할 것인가?
** 특별한 값을 확인해야 하는 코드가 복잡해짐
* 실행을 중지하고 **오류** 상태 **신호**를 보냄
** Python: 예외를 일으킴
+
[source, python]
----
raise Exception("descriptive string")
----

== 제어 흐름(Control flow)로서의 예외

* 오류가 발생했을 때 특별한 값을 반환하지 않고 `error value` 가 return 되었는지 확인
* 대신, 함수의 specification과 일치하는 결과를 생성할 수 없으면 예외를 발생시킴

[source, python]
----
raise <exceptionName>(<arguments>)
raise ValueError("something is wrong")
----

== 예제: Exception

[source, python]
----
def get_ratios(L1, L2):
    """ 가정: L1과 L2는 길이가 같은 list
        Return: L1[i]/L2[i] 를 포함하는 list """
    ratios = []
        for index in range(len(L1)):
        try:
            ratios.append(L1[index]/L2[index])
        except ZeroDivisionError:
            ratios.append(float('nan')) #nan = not a number
        except:
            raise ValueError('get_ratios called with bad arg')
    return ratios
----

== 예외 예

* 과목에 대한 주제 list가 주어졌다고 가정할 때, 각 항목은 두 부분으로 구성된 list가 된다
** 학생의 성, 이름으로 구성된 list
** 과제에 대한 성적 list

[source, python]
----
test_grades =   [[['peter', 'parker'], [80.0, 70.0, 85.0]],
                [['bruce', 'wayne'], [100.0, 80.0, 74.0]]]
----

* 이름, 성적 및 이름이 포함된 **새 수업 목록**을 만듦

[source, python]
----
[[['peter', 'parker'], [80.0, 70.0, 85.0], 78.33333],
[['bruce', 'wayne'], [100.0, 80.0, 74.0], 84.666667]]]
----

== 예제 코드

[source, python]
----
[[['peter', 'parker'], [80.0, 70.0, 85.0], 78.33333],
[['bruce', 'wayne'], [100.0, 80.0, 74.0], 84.666667]]]
----

[source, python]
----
def get_stats(class_list):
    new_stats = []
    for elt in class_list:
        new_stats.append([elt[0], elt[1], avg(elt[1])])
    return new_stats

def avg(grades):
    return sum(grades)/len(grades)
----

== 학생의 성적이 없는 오류

* 만약 **학생의 성적이 없는 경우**, 오류가 발생됨

[source, python]
----
test_grades = [ [['peter', 'parker'], [10.0, 5.0, 85.0]],
                [['bruce', 'wayne'], [10.0, 8.0, 74.0]],
                [['captain', 'america'], [8.0,10.0,96.0]],
                [['deadpool'], []] ]
----

* `ZeroDivisionError: float division by zero` 오류가 발생됨 +
오류 코드:

[source, python]
----
return sum(grades) / len(grades)
----

== Option 1: 오류 메시지를 `print` 하여 오류 표시

* 메시지를 사용하여 문제가 있음을 알리기로 결정

[source, python]
----
def avg(grades):
    try:
        return sum(grades)/len(grades)
        except ZeroDivisionError:
        print('warning: no grades data')
----

* 일부 테스트 데이터 실행:

[source, python]
----
warning: no grades data # 오류 표시
[[['peter', 'parker'], [10.0, 5.0, 85.0], 15.41666666],
[['bruce', 'wayne'], [10.0, 8.0, 74.0], 13.83333334],
[['captain', 'america'], [8.0, 10.0, 96.0], 17.5],
[['deadpool'], [], None]]   # avg 는 exception에서 어떤 것도 return 하지 않음
----

== Option 2: 정책 변경

* 성적이 없는 학생의 경우 `Zero` 로 설정

[source, python]
----
def avg(grades):
    try:
        return sum(grades)/len(grades)
    except ZeroDivisionError:
        print('warning: no grades data')
        return 0.0
----

* 일부 테스트 데이터 실행:

[source, python]
----
warning: no grades data # 여전히 오류 표시 
[[['peter', 'parker'], [10.0, 5.0, 85.0], 15.41666666],
[['bruce', 'wayne'], [10.0, 8.0, 74.0], 13.83333334],
[['captain', 'america'], [8.0, 10.0, 96.0], 17.5],
[['deadpool'], [], None]]   # avg 는 0을 return
----

== Assertions

* Computation 상태에 대한 `가정` 이 예상대로인지 확인하고 싶을 때
* 가정이 충족되지 않으면 `AssertionError` 예외를 발생시키기 위해 `Assert statement` 를 사용
* 좋은 방어적 프로그래밍의 예


== 예제

[source, python]
----
def avg(grades):
    assert len(grades) != 0, 'no grades data'
    return sum(grades)/len(grades)
----

* 성적에 대해 빈 리스트가 주어지면 `AssetionError` 가 발생
* 그 외의 경우 잘 수행됨

== 방어적 프로그래밍으로서의 Assertion

* Assertion은 프로그래머가 예상치 못한 상황에 대한 응답을 제어하는 것을 허용하지 않음
* 예상되는 조건이 충족되지 않을 때 마다 **실행이 중단**되도록 보장함
* 일반적으로 함수에 대한 **입력을 확인**하는데 사용되지만 어디에서나 사용할 수 있음
* 잘못된 값이 전파되는 것을 방지하기 위해 함수의 **출력을 확인**하는데 사용할 수 있음
* 버그의 원인을 더 쉽게 찾을 수 있음

== Asertion을 사용해야 할 때

* 목표는 버그를 발견하고 어디에서 발생했는지 명확히 하는 것
* 테스트의 **보충 자료**로 사용
* 사용자가 **잘못된 데이터 입력**을 제공하면 **예외**가 발생
* `Assertion` 을 사용하여
** argument 또는 값의 `타입` 을 확인
** 데이터 구조의 `불변성(invariants)` 이 충족되는지 확인
** return에 대한 `제약 조건(constraints)` 을 확인
** 절차상의 제약 조건 `위반` 여부 확인(예: 목록에 중복 항목이 없음)
